### ISSUE TITLE
invalid value encountered in true_divide

### ISSUE THREAD

**Issue by tamaraprieto** [parklab/PaSDqc#7]
Hi, 

I am getting the following error when running the program. 

This is the command:
`PaSDqc QC \
        -d test/ \
        -c PaSDqc-1.1.0-source/PaSDqc/db/categorical_spectra_0.1x.txt \
        -q 30 \
        -r TEST`

This is the std error
`
Processing: 1
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr1.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 1 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr1.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 1 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr1.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr1.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr1.map.pos
Processing: 2
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr2.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 2 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr2.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 2 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr2.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr2.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr2.map.pos
Processing: 3
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr3.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 3 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr3.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 3 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr3.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr3.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr3.map.pos
Processing: 4
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr4.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 4 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr4.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 4 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr4.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr4.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr4.map.pos
Processing: 5
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr5.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 5 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr5.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 5 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr5.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr5.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr5.map.pos
Processing: 6
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr6.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 6 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr6.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 6 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr6.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr6.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr6.map.pos
Processing: 7
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr7.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 7 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr7.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 7 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr7.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr7.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr7.map.pos
Processing: 8
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr8.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 8 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr8.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 8 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr8.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr8.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr8.map.pos
Processing: 9
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr9.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 9 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr9.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 9 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr9.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr9.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr9.map.pos
Processing: 10
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr10.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 10 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr10.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 10 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr10.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr10.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr10.map.pos
Processing: 11
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr11.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 11 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr11.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 11 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr11.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr11.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr11.map.pos
Processing: 12
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr12.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 12 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr12.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 12 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr12.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr12.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr12.map.pos
Processing: 13
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr13.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 13 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr13.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 13 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr13.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr13.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr13.map.pos
Processing: 14
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr14.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 14 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr14.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 14 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr14.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr14.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr14.map.pos
Processing: 15
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr15.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 15 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr15.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 15 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr15.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr15.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr15.map.pos
Processing: 16
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr16.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 16 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr16.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 16 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr16.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr16.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr16.map.pos
Processing: 17
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr17.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 17 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr17.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 17 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr17.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr17.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr17.map.pos
Processing: 18
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr18.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 18 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr18.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 18 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr18.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr18.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr18.map.pos
Processing: 19
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr19.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 19 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr19.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 19 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr19.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr19.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr19.map.pos
Processing: 20
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr20.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 20 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr20.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 20 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr20.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr20.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr20.map.pos
Processing: 21
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr21.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 21 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr21.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 21 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr21.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr21.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr21.map.pos
Processing: 22
Executing: samtools view -q 30 -L /PaSDqc/lib/python3.5/site-packages/PaSDqc/db/grch37.chr22.map.bed /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 22 | cut -f 3,4 | uniq > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr22.map.pos
Executing: samtools view -uh -q 30 /mnt/gluster/distributed/home/uvi/be/Single-Cell/RESULTS/PaSDqc/PaSDqc/TP-ML-F3-IP.dedup.ps.bam 22 | samtools depth -b PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr22.map.pos - > PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr22.map.pos.cov; rm PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr22.map.pos
PaSDqc/psd/TP-ML-F3-IP.dedup.ps.chroms.spec
1.p arm
/home/uvi/be/.local/lib/python3.5/site-packages/astropy/stats/lombscargle/implementations/fast_impl.py:93: RuntimeWarning:

divide by zero encountered in true_divide

/home/uvi/be/.local/lib/python3.5/site-packages/astropy/stats/lombscargle/implementations/fast_impl.py:93: RuntimeWarning:

invalid value encountered in true_divide

/home/uvi/be/.local/lib/python3.5/site-packages/astropy/stats/lombscargle/implementations/fast_impl.py:104: RuntimeWarning:

invalid value encountered in true_divide

/home/uvi/be/.local/lib/python3.5/site-packages/astropy/stats/lombscargle/implementations/fast_impl.py:122: RuntimeWarning:

invalid value encountered in true_divide

/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 3226 results

1.q arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 1 results

10.p arm
10.q arm
11.p arm
11.q arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 6986 results

12.p arm
12.q arm
13.p arm
13.q arm
14.p arm
14.q arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 7999 results

15.p arm
15.q arm
16.p arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 3221 results

16.q arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 5056 results

17.p arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 6323 results

17.q arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 7648 results

18.p arm
18.q arm
19.p arm
19.q arm
2.p arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 8000 results

2.q arm
/home/uvi/be/.local/lib/python3.5/site-packages/numpy/lib/function_base.py:4035: RuntimeWarning:

Invalid value encountered in median for 7759 results

20.p arm
20.q arm
21.p arm
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/PaSDqc/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/PaSDqc/bin/PaSDqc", line 102, in _build_and_save
    psd = PaSDqc.PSDTools.SamplePSD.build_from_dir(str(dir_in), sample=sample, clean=clean)
  File "/PaSDqc/lib/python3.5/site-packages/PaSDqc/PSDTools.py", line 268, in build_from_dir
    df = cls._build_dataframe(file_list, build)
  File "/PaSDqc/lib/python3.5/site-packages/PaSDqc/PSDTools.py", line 318, in _build_dataframe
    [psd.PSD_LS_chrom(f_cent, freq=freq) for psd in psd_list]
  File "/PaSDqc/lib/python3.5/site-packages/PaSDqc/PSDTools.py", line 318, in <listcomp>
    [psd.PSD_LS_chrom(f_cent, freq=freq) for psd in psd_list]
  File "/PaSDqc/lib/python3.5/site-packages/PaSDqc/PSDTools.py", line 207, in PSD_LS_chrom
    pwr_p, count_p = self.PSD_LS_manual(df_p, freq, l_seg, p_overlap, verbose=verbose)
  File "/PaSDqc/lib/python3.5/site-packages/PaSDqc/PSDTools.py", line 164, in PSD_LS_manual
    starts, ends = ChromPSD._welch_seg_bounds(df.pos, l_seg, p_overlap)
  File "/PaSDqc/lib/python3.5/site-packages/PaSDqc/PSDTools.py", line 59, in _welch_seg_bounds
    ends[-1] = pos.iloc[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/PaSDqc/bin/PaSDqc", line 265, in <module>
    args.func(args)
  File "/PaSDqc/bin/PaSDqc", line 210, in QC
    PSD(args)
  File "/PaSDqc/bin/PaSDqc", line 95, in PSD
    [p.get() for p in res]
  File "/PaSDqc/bin/PaSDqc", line 95, in <listcomp>
    [p.get() for p in res]
  File "/PaSDqc/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: index -1 is out of bounds for axis 0 with size 0`

Do you have any idea about what can be happening here?
I just find this error for some of the single-cells, not all of them.
Thanks in advance

**Comment by maxwellsh** [comment]
Hmm, looks like it's failing when trying to analyze 21p. The problem appears to be that there is no depth information for that chromosome arm. My guess is you may have very little (or no) coverage of that chromosome arm. You can check this by loading PaSDqc/cov/TP-ML-F3-IP.dedup.ps.chr21.map.pos.cov and plotting the pos column vs the depth column. I expect you will find virtually no reads on 22p.

Please let me know if this is the case. If not, we can troubleshoot further.

**Comment by tamaraprieto** [comment]
Coverage is quite low indeed. Here you are the plot:

![chr21 depth](https://user-images.githubusercontent.com/7628968/39518042-f8a075e4-4e01-11e8-89f3-ed53eaab3094.png)

Is it not possible to run PaSDqc in such conditions?

**Comment by maxwellsh** [comment]
Unfortunately not. With such sparse coverage, the amplification patterns
cannot be accurately inferred. Indeed, if the cell was sequenced to e.g. 1X
average coverage, but one chromosome has such low coverage PaSDqc cannot
function, that itself is indicative of a low quality sample.

**Comment by tamaraprieto** [comment]
OK, thank you. Could you please consider to issue a warning under these circumstances so the user knows what is going on?

**Comment by maxwellsh** [comment]
Yes, I will do. Thank you for pointing out this issue!
